In [31]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pandas as pd

from layer import HiddenLayer
from activations import *

random.seed(42)
np.random.seed(42)


In [32]:
layer = HiddenLayer(3, 3, sigmoid) #bo come gli passo una funzione dopo vedo
print(layer)

HiddenLayer(num_units=3, num_inputs=3, activation=sigmoid)
W=[[-0.12545988  0.45071431  0.23199394]
 [ 0.09865848 -0.34398136 -0.34400548]
 [-0.44191639  0.36617615  0.10111501]]
b=[[ 0.20807258 -0.47941551  0.46990985]])


In [33]:
out = layer.forward(np.array([[1, 2, 3]]))
out

array([[0.26002868, 0.59432272, 0.57865095]])

In [34]:
layer2 = HiddenLayer(3, 4, sigmoid)
print(layer2)



HiddenLayer(num_units=4, num_inputs=3, activation=sigmoid)
W=[[ 0.33244264 -0.28766089 -0.31817503 -0.31659549]
 [-0.19575776  0.02475643 -0.06805498 -0.20877086]
 [ 0.11185289 -0.36050614 -0.20785535 -0.13363816]]
b=[[-0.04393002  0.28517596 -0.30032622  0.01423444]])


In [35]:
out2 = layer2.forward(out)
print(out2)

[[0.49772379 0.5041204  0.36730796 0.43303069]]


In [36]:
print(out.shape)
print(layer2.W.shape)

(1, 3)
(3, 4)


In [37]:
mse(3, 1)

4.0

In [38]:
data = pd.read_csv('data/ML-CUP23-TR.csv', sep=';', header=None)
data = data.to_numpy()

#plot the data
plt.pyplot.scatter(data[:, 0], data[:, 1], c=data[:, 2])
plt.pyplot.show()





AttributeError: module 'matplotlib.pyplot' has no attribute 'pyplot'