In [1]:
import numpy as np
import random

from layer import HiddenLayer
from activations import *

random.seed(42)
np.random.seed(42)


In [2]:
layer = HiddenLayer(3, 3, sigmoid) #bo come gli passo una funzione dopo vedo
print(layer)

HiddenLayer(num_units=3, num_inputs=3, activation=sigmoid)
W=[[-0.12545988  0.45071431  0.23199394]
 [ 0.09865848 -0.34398136 -0.34400548]
 [-0.44191639  0.36617615  0.10111501]]
b=[[ 0.20807258 -0.47941551  0.46990985]])


In [3]:
out = layer.forward(np.array([[1, 2, 3]]))
out

array([[0.26002868, 0.59432272, 0.57865095]])

In [5]:
layer2 = HiddenLayer(3, 4, sigmoid)
print(layer2)



HiddenLayer(num_units=4, num_inputs=3, activation=sigmoid)
W=[[ 0.09241457 -0.45354959  0.10754485 -0.32947588]
 [-0.43494841  0.44888554  0.46563203  0.30839735]
 [-0.19538623 -0.40232789  0.18423303 -0.05984751]]
b=[[-0.37796177 -0.00482309 -0.46561148  0.4093204 ]])


In [6]:
out2 = layer2.forward(out)
print(out2)

[[0.32618487 0.47781869 0.48642723 0.61592893]]
